# Programming Assignment 1 - OpenCV Exercises Image Enhancement

by Mark Jeremy G. Narag

This Programming Assignment has seven (7) parts which tackles 7 different tasks. This is PART 1.


All codes were executed using Jupyter Notebook in Macbook Air M1 MacOS Ventura 13.4.1

## PART 1: Program that performs the computations described below:

### (a) Select a negative floating-point number. Take its absolute value, round it, and then take its ceiling and floor. Print the results to screen.

In [1]:
number = -3.45

# Calculate the absolute value
abs_value = abs(number)

# Round the absolute value
rounded_value = round(abs_value)

# Calculate the ceiling and floor
ceiling_value = int(abs_value) + 1
floor_value = int(abs_value)

# Print the results
print(f"Original Number: {number}")
print(f"Absolute Value: {abs_value}")
print(f"Rounded Value: {rounded_value}")
print(f"Ceiling Value: {ceiling_value}")
print(f"Floor Value: {floor_value}")


Original Number: -3.45
Absolute Value: 3.45
Rounded Value: 3
Ceiling Value: 4
Floor Value: 3


### (b) Generate a 3 × 4 matrix whose elements are random integers. Print the matrix.

In [2]:
import random

# Define the dimensions of the matrix
rows = 3
columns = 4

# Initialize an empty matrix
matrix = []

# Populate the matrix with random integers
for i in range(rows):
    row = []
    for j in range(columns):
        # Generate a random integer and add it to the row
        row.append(random.randint(1, 100))  # Change the range as needed
    matrix.append(row)

# Print the matrix
for row in matrix:
    print(row)


[62, 38, 99, 70]
[66, 76, 44, 71]
[35, 51, 28, 44]



### (c) Declare matrix variables A, B and integer variable c within OpenCV. Assign them with the following values:
    
    A = ((6,0,2) (2,6,5) (9,7,1)
         (1,6,4) (5,4,9) (6,9,2)
         (3,5,9) (5,3,7) (8,3,3))
         
         
    B = ((9,1,9) (7,0,5) (2,0,3)
         (9,2,3) (4,3,6) (0,2,9)
         (7,2,6) (0,3,8) (4,2,1))
    c = 0.7
    d = 0.55

In [59]:
#!pip install opencv-python==4.7.0.72
import cv2
import numpy as np

A = np.array([[(6,0,2), (2,6,5), (9,7,1)],
     [(1,6,4), (5,4,9), (6,9,2)],
     [(3,5,9), (5,3,7), (8,3,3)]], dtype=np.uint8)  # Specify the data type (e.g., uint8 for 8-bit integers)
A = cv2.Mat(A)

B = np.array([[(9,1,9), (7,0,5), (2,0,3)],
     [(9,2,3), (4,3,6), (0,2,9)],
     [(7,2,6), (0,3,8), (4,2,1)]], dtype=np.uint8)
B = cv2.Mat(B)

c = 0.7
d = 0.55

### Compute the following: 

### i. cA+(1−c)B+d

In [60]:
x = c*A + ((1-c)*B) + d
print("x=")
print(x)

x=
[[[7.45 0.85 4.65]
  [4.05 4.75 5.55]
  [7.45 5.45 2.15]]

 [[3.95 5.35 4.25]
  [5.25 4.25 8.65]
  [4.75 7.45 4.65]]

 [[4.75 4.65 8.65]
  [4.05 3.55 7.85]
  [7.35 3.25 2.95]]]


### ii. A^−1 (using SVD)

In [61]:
U, S, Vt = np.linalg.svd(A)
S_inv = np.zeros_like(A, dtype=float)
S_inv[:len(S)] = 1 / S
A_inverse = Vt.T @ S_inv @ U.T
print("Inverse of matrix A:")
print(A_inverse)

Inverse of matrix A:
[[[ 0.95386233  0.85608027  0.72918466]
  [ 0.53737483  0.43981643  0.349763  ]
  [ 0.52661874  0.4807873   0.41407813]]

 [[-0.02246405  0.36323647  0.59831343]
  [ 0.04156504  0.0608089   0.17032046]
  [ 0.09108729 -0.596499   -0.89867205]]

 [[-0.36809977  0.32970098 -0.13537423]
  [ 0.28509763 -0.23585013  0.11991207]
  [-0.19189696  0.18423042 -0.06131238]]]


### iii. Eigenvalue of B

In [106]:
import cv2
import numpy as np

#I will first decompose the vector B
B_1 = np.array([[9, 7, 2],
                [ 9, 4, 0],
                [7, 0, 4]], np.float32)
B_2 = np.array([[1, 0, 0],
                [2, 3, 2],
                [2, 3, 2]], np.float32)
B_3 = np.array([[9, 5, 3],
                [3, 6, 9],
                [6, 8, 1]], np.float32)

B1 = cv2.eigenNonSymmetric(B_1) #note that our matrix is non symmetric so it is important to use eigenNonSymmetric
B2 = cv2.eigenNonSymmetric(B_2)
B3 = cv2.eigenNonSymmetric(B_3)
print('Eigenvalues=',[((B1[0][0][0]),(B1[0][1][0]),(B1[0][2][0])),
     ((B2[0][0][0]),(B2[0][1][0]),(B2[0][2][0])),
     ((B3[0][0][0]),(B3[0][1][0]),(B3[0][2][0]))])

Eigenvalues= [(15.624144, 4.0, -2.6241438), (5.0, 1.0, -3.1401849e-16), (16.814648, 4.3327074, -5.147355)]


### (iv) solve the matrix equation Ax = b where

    b = ((3,5,5)
         (7,2,8)
         (4,1,6))

In [134]:
#I will first decompose the vector A and b
A_1 = np.array([[6, 2, 9],
                [1, 5, 6],
                [3, 5, 8]], np.float32)
A_2 = np.array([[0, 6, 7],
                [6, 4, 9],
                [5, 3, 3]], np.float32)
A_3 = np.array([[2, 5, 1],
                [4, 9, 2],
                [9, 7, 3]], np.float32)
b_1 = np.array([[3],
              [7],
              [4]], np.float32)
b_2 = np.array([[5],
              [2],
              [1]], np.float32)
b_3 = np.array([[5],
              [8],
              [6]], np.float32)

# solving for x using numPy's linear algebra functions
x_1 = cv2.solve(A_1, b_1, flags=cv2.DECOMP_SVD)
x_2 = cv2.solve(A_2, b_2, flags=cv2.DECOMP_SVD)
x_3 = cv2.solve(A_3, b_3, flags=cv2.DECOMP_SVD)

# Print the solution x
print("Solution x =")
print([(x_1[1][0][0], x_2[1][0][0], x_3[1][0][0])])
print([(x_1[1][1][0], x_2[1][1][0], x_3[1][1][0])])
print([(x_1[1][2][0], x_2[1][2][0], x_3[1][2][0])])

Solution x =
[(-10.100011, -0.2905405, 2.3333251)]
[(-6.9000087, 0.7229729, 1.9999962)]
[(8.600008, 0.09459456, -9.666633)]


### (d) Create a 2D matrix with three channels of type byte and size 100-by-100 and set all values to zero. Draw a red rectangle between with corners (30, 10) and (60, 40). Display this image.

In [54]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# creating 3-channel of size 100x100 matrix with all values set to zero
image = np.zeros((100, 100, 3), dtype=np.uint8) 

# draw the red rectangle
cv2.rectangle(image, (30, 10), (60, 40), (0, 0, 255), 1)  #(0,0,255) is red and 1 is the thickness of line
#remember that in cv2, the arrangement of channel is B-G-R

# displaying the image
cv2.imshow('Red rectangle', image)

cv2.waitKey(0)
cv2.destroyAllWindows()#closing all windows
cv2.waitKey(1) #for some reason, macbook jupyter does not close the windows and I saw a discussion online 
cv2.waitKey(1) #regarding adding these extra lines
cv2.waitKey(1)
cv2.waitKey(1)


-1

### (e) Copy the red channel in (d) above into another matrix for display as grayscale image.

In [58]:
# creating a grayscale image from the red channel
red_channel = image[:, :, 2] #red is on the last channel

# displaying the image
cv2.imshow('Red in grayscale', red_channel)

cv2.waitKey(0)
cv2.destroyAllWindows()#closing all windows
cv2.waitKey(1) #for some reason, macbook jupyter does not close the windows and I saw a discussion online 
cv2.waitKey(1) #regarding adding these extra lines
cv2.waitKey(1)
cv2.waitKey(1)


-1